[project]
name = 'Guideme'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.Guideme]
path = 'contracts/Guideme.clar'
clarity_version = 3
epoch = 3.1
[contracts.GuideFavorites]
path = 'contracts/GuideFavorites.clar'
clarity_version = 3
epoch = 3.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
